os: Visual Studio 2017

# NOTE .NET Core SDK preview2 is already installed in the build worker image Visual Studio 2015
# so the `install` section is not required

environment:
  CLI_VERSION: 2.0.0

install:
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Syrx/Syrx/master/dotnet-install.ps1" -OutFile "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1"
  - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Version $env:CLI_VERSION -InstallDir $env:DOTNET_INSTALL_DIR'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  # dotnet info
  - ps: dotnet --info  
  - ps: dotnet restore
  - ps: dotnet build .\Syrx.sln
  - ps: Pop-Location

version: 1.0.0.{build}