namespace Syrx.Oracle.Tests.Integration
{
    public static class OracleCommandStrings
    {
        public const string Alias = "Syrx.Oracle";

        public static class Setup
        {
            public const string CreateDatabase = "CREATE DATABASE Syrx";

            public const string DropTableCreatorProcedure = @"
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_exists
    FROM user_objects
    WHERE object_type = 'PROCEDURE' AND object_name = 'USP_CREATE_TABLE';

    IF v_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP PROCEDURE USP_CREATE_TABLE';
        DBMS_OUTPUT.PUT_LINE('Procedure dropped successfully.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Procedure does not exist.');
    END IF;
END;
";

            public const string CreateTableCreatorProcedure = @"
CREATE OR REPLACE PROCEDURE usp_create_table(p_name IN VARCHAR2) IS
    v_exists NUMBER;
BEGIN
    -- Check if the table exists
    SELECT COUNT(*)
    INTO v_exists
    FROM user_tables
    WHERE table_name = UPPER(p_name);

    IF v_exists > 0 THEN
        -- Table exists, drop it
        EXECUTE IMMEDIATE 'DROP TABLE ' || p_name;
    ELSE
        -- Table doesn't exist, create it
        EXECUTE IMMEDIATE '
            CREATE TABLE ' || p_name || ' (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                name VARCHAR2(50),
                value NUMBER(18, 2),
                modified DATE
            )';
    END IF;
END;
";

            //public const string CreateTable = @"exec usp_create_table(name);";

            public const string CreatePocoTableProcedure = @"CREATE OR REPLACE PROCEDURE create_poco_table AS
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE poco (
                        id NUMBER GENERATED ALWAYS AS IDENTITY,
                        name VARCHAR2(50),
                        value NUMBER(18, 2),
                        modified DATE
                    )';
            END;
            ";


            public const string ExecutePocoTableProcedure = @"DECLARE
    v_name VARCHAR2(50) := 'poco'; -- Replace with your desired name
BEGIN
    EXECUTE create_poco_table(v_name);
END;";


            public const string CreateIdentityTesterTable = @"CREATE OR REPLACE PROCEDURE create_identity_tester AS
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE identity_tester (
            id NUMBER GENERATED ALWAYS AS IDENTITY,
            name VARCHAR2(50),
            value NUMBER(18, 2),
            modified DATE
        )';
END;
";

            public const string CreateBulkInsertTable = @"CREATE OR REPLACE PROCEDURE create_bulk_insert AS
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE bulk_insert (
            id NUMBER GENERATED ALWAYS AS IDENTITY,
            name VARCHAR2(50),
            value NUMBER(18, 2),
            modified DATE
        )';
END;
";
            public const string CreateDistributedTransactionTable = @"CREATE OR REPLACE PROCEDURE create_distributed_transaction AS
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE distributed_transaction (
            id NUMBER GENERATED ALWAYS AS IDENTITY,
            name VARCHAR2(50),
            value NUMBER(18, 2),
            modified DATE
        )';
END;
";

            //public const string DropIdentityTesterProcedure = "DROP FUNCTION usp_identity_tester";

            public const string DropIdentityTesterProcedure = @"
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_exists
    FROM user_objects
    WHERE object_type = 'PROCEDURE' AND object_name = 'usp_identity_tester';

    IF v_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP PROCEDURE usp_identity_tester';
        DBMS_OUTPUT.PUT_LINE('Procedure dropped successfully.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Procedure does not exist.');
    END IF;
END;
";

            public const string CreateIdentityTesterProcedure = @"
CREATE OR REPLACE FUNCTION usp_identity_tester(_name IN VARCHAR2, _value IN NUMBER)
RETURN sys.odcinumberlist PIPELINED
IS
    _id NUMBER;
BEGIN
    INSERT INTO identity_test(name, value, modified)
    VALUES (_name, _value, CURRENT_TIMESTAMP)
    RETURNING id INTO _id;

    PIPE ROW(_id);
    RETURN;
END;
";

            //public const string DropBulkInsertProcedure = "DROP PROCEDURE usp_bulk_insert";

            public const string DropBulkInsertProcedure = @"
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_exists
    FROM user_objects
    WHERE object_type = 'PROCEDURE' AND object_name = 'usp_bulk_insert';

    IF v_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP PROCEDURE usp_bulk_insert';
        DBMS_OUTPUT.PUT_LINE('Procedure dropped successfully.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Procedure does not exist.');
    END IF;
END;
";

            public const string CreateBulkInsertProcedure = @"CREATE OR REPLACE PROCEDURE usp_bulk_insert(p_path IN VARCHAR2) IS
    v_command VARCHAR2(32767);
    v_template VARCHAR2(32767) := 'BEGIN
        EXECUTE IMMEDIATE ''BULK INSERT bulk_insert FROM ''''%path'''' WITH (fieldterminator = '''','''', rowterminator = ''''\n'''')'';
    END;';
BEGIN
    v_command := REPLACE(v_template, '%path', p_path);
    EXECUTE IMMEDIATE v_command;
END;
";

            //public const string DropBulkInsertAndReturnProcedure = "DROP PROCEDURE usp_bulk_insert_and_return";

            public const string DropBulkInsertAndReturnProcedure = @"
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_exists
    FROM user_objects
    WHERE object_type = 'PROCEDURE' AND object_name = 'usp_bulk_insert_and_return';

    IF v_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP PROCEDURE usp_bulk_insert_and_return';
        DBMS_OUTPUT.PUT_LINE('Procedure dropped successfully.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Procedure does not exist.');
    END IF;
END;
";

            public const string CreateBulkInsertAndReturnProcedure = @"CREATE OR REPLACE PROCEDURE usp_bulk_insert_and_return(p_path IN VARCHAR2) IS
    v_command VARCHAR2(32767);
    v_template VARCHAR2(32767) := 'BEGIN
        EXECUTE IMMEDIATE ''BULK INSERT bulk_insert FROM ''''%path'''' WITH (fieldterminator = '''','''', rowterminator = ''''\n'''')'';
    END;';
BEGIN
    v_command := REPLACE(v_template, '%path', p_path);
    EXECUTE IMMEDIATE v_command;

    -- Assuming you want to return all rows from the bulk_insert table
    FOR rec IN (SELECT * FROM bulk_insert) LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || rec.id || ', Name: ' || rec.name || ', Value: ' || rec.value || ', Modified: ' || rec.modified);
    END LOOP;
END;
";

            //public const string DropTableClearingProcedure = "DROP PROCEDURE usp_clear_table";

            public const string DropTableClearingProcedure = @"
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_exists
    FROM user_objects
    WHERE object_type = 'PROCEDURE' AND object_name = 'usp_clear_table';

    IF v_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP PROCEDURE usp_clear_table';
        DBMS_OUTPUT.PUT_LINE('Procedure dropped successfully.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Procedure does not exist.');
    END IF;
END;
";

            public const string CreateTableClearingProcedure = @"CREATE OR REPLACE PROCEDURE usp_clear_table(name IN VARCHAR2) IS
    v_sql VARCHAR2(32767);
BEGIN
    v_sql := 'TRUNCATE TABLE ' || p_name;
    EXECUTE IMMEDIATE v_sql;
    DBMS_OUTPUT.PUT_LINE('Table ' || p_name || ' truncated successfully.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error truncating table: ' || SQLERRM);
END;
";

            public const string ClearTable = @"
truncate table poco
";

            public const string Populate = "INSERT INTO poco(name, value, modified) VALUES (:Name, :Value, SYSTIMESTAMP)";
        }


        public static class Query
        {

            public static class Multimap
            {

                public const string ExceptionsAreReturnedToCaller = @"SELECT 1/0;";

                public const string SingleType = @"SELECT id AS ""Id"",
       name AS ""Name"",
       value AS ""Value"",
       modified AS ""Modified""
FROM poco;";

                public const string SingleTypeWithParameters = @"SELECT id AS ""Id"",
       name AS ""Name"",
       value AS ""Value"",
       modified AS ""Modified""
FROM poco
WHERE id = @id;";

                public const string TwoTypes = @"SELECT a.id,
       a.name AS ""Name"",
       a.value AS ""Value"",
       a.modified AS ""Modified"",
       b.id AS ""Id"",
       b.name,
       b.value,
       b.modified
FROM poco a
JOIN (
    SELECT id,
           name,
           value,
           modified
    FROM poco
) b ON b.id = (a.id + 10);";

                public const string TwoTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
WHERE one.""Id"" = :id;
";

                public const string ThreeTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
WHERE one.""Id"" = :id;

";

                public const string FourTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
JOIN data four ON four.""Id"" = (three.""Id"" + 1)
WHERE one.""Id"" = :id;

";

                public const string FiveTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
JOIN data four ON four.""Id"" = (three.""Id"" + 1)
JOIN data five ON five.""Id"" = (four.""Id"" + 1)
WHERE one.""Id"" = :id;

";

                public const string SixTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
JOIN data four ON four.""Id"" = (three.""Id"" + 1)
JOIN data five ON five.""Id"" = (four.""Id"" + 1)
JOIN data six ON six.""Id"" = (five.""Id"" + 1)
WHERE one.""Id"" = :id;

";

                public const string SevenTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
JOIN data four ON four.""Id"" = (three.""Id"" + 1)
JOIN data five ON five.""Id"" = (four.""Id"" + 1)
JOIN data six ON six.""Id"" = (five.""Id"" + 1)
JOIN data seven ON seven.""Id"" = (six.""Id"" + 1)
WHERE one.""Id"" = :id;
";

                public const string EightTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
JOIN data four ON four.""Id"" = (three.""Id"" + 1)
JOIN data five ON five.""Id"" = (four.""Id"" + 1)
JOIN data six ON six.""Id"" = (five.""Id"" + 1)
JOIN data seven ON seven.""Id"" = (six.""Id"" + 1)
JOIN data eight ON eight.""Id"" = (seven.""Id"" + 1)
WHERE one.""Id"" = :id;

";

                public const string NineTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
JOIN data four ON four.""Id"" = (three.""Id"" + 1)
JOIN data five ON five.""Id"" = (four.""Id"" + 1)
JOIN data six ON six.""Id"" = (five.""Id"" + 1)
JOIN data seven ON seven.""Id"" = (six.""Id"" + 1)
JOIN data eight ON eight.""Id"" = (seven.""Id"" + 1)
JOIN data nine ON nine.""Id"" = (eight.""Id"" + 1)
WHERE one.""Id"" = :id;
";

                public const string TenTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
JOIN data four ON four.""Id"" = (three.""Id"" + 1)
JOIN data five ON five.""Id"" = (four.""Id"" + 1)
JOIN data six ON six.""Id"" = (five.""Id"" + 1)
JOIN data seven ON seven.""Id"" = (six.""Id"" + 1)
JOIN data eight ON eight.""Id"" = (seven.""Id"" + 1)
JOIN data nine ON nine.""Id"" = (eight.""Id"" + 1)
JOIN data ten ON ten.""Id"" = (nine.""Id"" + 1)
WHERE one.""Id"" = :id;
";

                public const string ElevenTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
JOIN data four ON four.""Id"" = (three.""Id"" + 1)
JOIN data five ON five.""Id"" = (four.""Id"" + 1)
JOIN data six ON six.""Id"" = (five.""Id"" + 1)
JOIN data seven ON seven.""Id"" = (six.""Id"" + 1)
JOIN data eight ON eight.""Id"" = (seven.""Id"" + 1)
JOIN data nine ON nine.""Id"" = (eight.""Id"" + 1)
JOIN data ten ON ten.""Id"" = (nine.""Id"" + 1)
JOIN data eleven ON eleven.""Id"" = (ten.""Id"" + 1)
WHERE one.""Id"" = :id;
";

                public const string TwelveTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
JOIN data four ON four.""Id"" = (three.""Id"" + 1)
JOIN data five ON five.""Id"" = (four.""Id"" + 1)
JOIN data six ON six.""Id"" = (five.""Id"" + 1)
JOIN data seven ON seven.""Id"" = (six.""Id"" + 1)
JOIN data eight ON eight.""Id"" = (seven.""Id"" + 1)
JOIN data nine ON nine.""Id"" = (eight.""Id"" + 1)
JOIN data ten ON ten.""Id"" = (nine.""Id"" + 1)
JOIN data eleven ON eleven.""Id"" = (ten.""Id"" + 1)
JOIN data twelve ON twelve.""Id"" = (eleven.""Id"" + 1)
WHERE one.""Id"" = :id;

";

                public const string ThirteenTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
JOIN data four ON four.""Id"" = (three.""Id"" + 1)
JOIN data five ON five.""Id"" = (four.""Id"" + 1)
JOIN data six ON six.""Id"" = (five.""Id"" + 1)
JOIN data seven ON seven.""Id"" = (six.""Id"" + 1)
JOIN data eight ON eight.""Id"" = (seven.""Id"" + 1)
JOIN data nine ON nine.""Id"" = (eight.""Id"" + 1)
JOIN data ten ON ten.""Id"" = (nine.""Id"" + 1)
JOIN data eleven ON eleven.""Id"" = (ten.""Id"" + 1)
JOIN data twelve ON twelve.""Id"" = (eleven.""Id"" + 1)
JOIN data thirteen ON thirteen.""Id"" = (twelve.""Id"" + 1)
WHERE one.""Id"" = :id;

";

                public const string FourteenTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
JOIN data four ON four.""Id"" = (three.""Id"" + 1)
JOIN data five ON five.""Id"" = (four.""Id"" + 1)
JOIN data six ON six.""Id"" = (five.""Id"" + 1)
JOIN data seven ON seven.""Id"" = (six.""Id"" + 1)
JOIN data eight ON eight.""Id"" = (seven.""Id"" + 1)
JOIN data nine ON nine.""Id"" = (eight.""Id"" + 1)
JOIN data ten ON ten.""Id"" = (nine.""Id"" + 1)
JOIN data eleven ON eleven.""Id"" = (ten.""Id"" + 1)
JOIN data twelve ON twelve.""Id"" = (eleven.""Id"" + 1)
JOIN data thirteen ON thirteen.""Id"" = (twelve.""Id"" + 1)
JOIN data fourteen ON fourteen.""Id"" = (thirteen.""Id"" + 1)
WHERE one.""Id"" = :id;
";

                public const string FifteenTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
JOIN data four ON four.""Id"" = (three.""Id"" + 1)
JOIN data five ON five.""Id"" = (four.""Id"" + 1)
JOIN data six ON six.""Id"" = (five.""Id"" + 1)
JOIN data seven ON seven.""Id"" = (six.""Id"" + 1)
JOIN data eight ON eight.""Id"" = (seven.""Id"" + 1)
JOIN data nine ON nine.""Id"" = (eight.""Id"" + 1)
JOIN data ten ON ten.""Id"" = (nine.""Id"" + 1)
JOIN data eleven ON eleven.""Id"" = (ten.""Id"" + 1)
JOIN data twelve ON twelve.""Id"" = (eleven.""Id"" + 1)
JOIN data thirteen ON thirteen.""Id"" = (twelve.""Id"" + 1)
JOIN data fourteen ON fourteen.""Id"" = (thirteen.""Id"" + 1)
JOIN data fifteen ON fifteen.""Id"" = (fourteen.""Id"" + 1)
WHERE one.""Id"" = :id;
";

                public const string SixteenTypesWithParameters = @"WITH data AS (
    SELECT id AS ""Id"",
           name AS ""Name"",
           value AS ""Value"",
           modified AS ""Modified""
    FROM poco
)
SELECT *
FROM data one
JOIN data two ON two.""Id"" = (one.""Id"" + 1)
JOIN data three ON three.""Id"" = (two.""Id"" + 1)
JOIN data four ON four.""Id"" = (three.""Id"" + 1)
JOIN data five ON five.""Id"" = (four.""Id"" + 1)
JOIN data six ON six.""Id"" = (five.""Id"" + 1)
JOIN data seven ON seven.""Id"" = (six.""Id"" + 1)
JOIN data eight ON eight.""Id"" = (seven.""Id"" + 1)
JOIN data nine ON nine.""Id"" = (eight.""Id"" + 1)
JOIN data ten ON ten.""Id"" = (nine.""Id"" + 1)
JOIN data eleven ON eleven.""Id"" = (ten.""Id"" + 1)
JOIN data twelve ON twelve.""Id"" = (eleven.""Id"" + 1)
JOIN data thirteen ON thirteen.""Id"" = (twelve.""Id"" + 1)
JOIN data fourteen ON fourteen.""Id"" = (thirteen.""Id"" + 1)
JOIN data fifteen ON fifteen.""Id"" = (fourteen.""Id"" + 1)
JOIN data sixteen ON sixteen.""Id"" = (fifteen.""Id"" + 1)
WHERE one.""Id"" = :id;
";
            }

            public static class Multiple
            {

                public const string OneTypeMultiple = @"select * from poco where id < 2;";

                public const string TwoTypeMultiple = @"
select * from poco where id < 2;
select * from poco where id < 3;
";

                public const string ThreeTypeMultiple = @"
select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
";

                public const string FourTypeMultiple = @"
select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
select * from poco where id < 5;
";

                public const string FiveTypeMultiple = @"select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
select * from poco where id < 5;
select * from poco where id < 6;
";

                public const string SixTypeMultiple = @"select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
select * from poco where id < 5;
select * from poco where id < 6;
select * from poco where id < 7;
";

                public const string SevenTypeMultiple = @"select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
select * from poco where id < 5;
select * from poco where id < 6;
select * from poco where id < 7;
select * from poco where id < 8;
";

                public const string EightTypeMultiple = @"select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
select * from poco where id < 5;
select * from poco where id < 6;
select * from poco where id < 7;
select * from poco where id < 8;
select * from poco where id < 9;
";

                public const string NineTypeMultiple = @"select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
select * from poco where id < 5;
select * from poco where id < 6;
select * from poco where id < 7;
select * from poco where id < 8;
select * from poco where id < 9;
select * from poco where id < 10;
";

                public const string TenTypeMultiple = @"select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
select * from poco where id < 5;
select * from poco where id < 6;
select * from poco where id < 7;
select * from poco where id < 8;
select * from poco where id < 9;
select * from poco where id < 10;
select * from poco where id < 11;
";

                public const string ElevenTypeMultiple = @"
select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
select * from poco where id < 5;
select * from poco where id < 6;
select * from poco where id < 7;
select * from poco where id < 8;
select * from poco where id < 9;
select * from poco where id < 10;
select * from poco where id < 11;
select * from poco where id < 12;
";

                public const string TwelveTypeMultiple = @"
select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
select * from poco where id < 5;
select * from poco where id < 6;
select * from poco where id < 7;
select * from poco where id < 8;
select * from poco where id < 9;
select * from poco where id < 10;
select * from poco where id < 11;
select * from poco where id < 12;
select * from poco where id < 13;
";

                public const string ThirteenTypeMultiple = @"
select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
select * from poco where id < 5;
select * from poco where id < 6;
select * from poco where id < 7;
select * from poco where id < 8;
select * from poco where id < 9;
select * from poco where id < 10;
select * from poco where id < 11;
select * from poco where id < 12;
select * from poco where id < 13;
select * from poco where id < 14;
";

                public const string FourteenTypeMultiple = @"
select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
select * from poco where id < 5;
select * from poco where id < 6;
select * from poco where id < 7;
select * from poco where id < 8;
select * from poco where id < 9;
select * from poco where id < 10;
select * from poco where id < 11;
select * from poco where id < 12;
select * from poco where id < 13;
select * from poco where id < 14;
select * from poco where id < 15;
";

                public const string FifteenTypeMultiple = @"
select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
select * from poco where id < 5;
select * from poco where id < 6;
select * from poco where id < 7;
select * from poco where id < 8;
select * from poco where id < 9;
select * from poco where id < 10;
select * from poco where id < 11;
select * from poco where id < 12;
select * from poco where id < 13;
select * from poco where id < 14;
select * from poco where id < 15;
select * from poco where id < 16;
";

                public const string SixteenTypeMultiple = @"
select * from poco where id < 2;
select * from poco where id < 3;
select * from poco where id < 4;
select * from poco where id < 5;
select * from poco where id < 6;
select * from poco where id < 7;
select * from poco where id < 8;
select * from poco where id < 9;
select * from poco where id < 10;
select * from poco where id < 11;
select * from poco where id < 12;
select * from poco where id < 13;
select * from poco where id < 14;
select * from poco where id < 15;
select * from poco where id < 16;
select * from poco where id < 17;
";
            }

        }

        public static class Execute
        {
            public const string ExceptionsAreReturnedToCaller = @"SELECT 1/0;";

            public const string SupportParameterlessCalls = @"CREATE TEMP TABLE result (
    Value int
);
INSERT INTO result (Value) VALUES (1);
SELECT * FROM result;
DROP TABLE result;";

            public const string SupportsRollbackOnParameterlessCallsCount = @"SELECT count(1) AS result FROM poco;";

            public const string SupportsRollbackOnParameterlessCalls = @"BEGIN;
DELETE FROM poco;
-- This will cause an error and rollback in a transaction block
SELECT 1 / 0;
ROLLBACK;";

            public const string SupportsSuppressedDistributedTransactions = @"INSERT INTO poco (name, value, modified)
VALUES (@Name, @Value, @Modified);";

            public const string SupportsTransactionRollbackCount = @"SELECT * FROM poco WHERE name = @Name;";

            public const string SupportsTransactionRollback = @"INSERT INTO poco (name, value)
VALUES (@Name, @Value * POWER(@Value, @Value));
";

            public const string SupportsEnlistingInAmbientTransactions = @"
INSERT INTO distributed_transaction (name, value, modified)
VALUES (@Name, @Value, @Modified);
";
            public const string SuccessfullyWithResponse = @"
INSERT INTO poco (name, value, modified)
VALUES (@Name, @Value, @Modified);
";
            public const string SuccessfullyWithResponseResponse = @"SELECT id, name, value, modified FROM poco WHERE name = @Name;";

            public const string Successful = @"
INSERT INTO poco (name, value, modified)
VALUES (@Name, @Value, @Modified);
";

            public const string SingleType = @"
INSERT INTO poco (name, value, modified)
VALUES (@Name, @Value, @Modified);
";
        }

        public static class Dispose
        {
            public const string Successfully = @"SELECT floor(random() * 100)::int;";
        }
    }
}